// Generated by scripts/sync-demo-data.mjs.
// Do not edit this file directly.
export interface AaplRow {
  readonly Date: Date
  readonly Open: number
  readonly High: number
  readonly Low: number
  readonly Close: number
  readonly "Adj Close": number
  readonly Volume: number
}

export declare const aapl: readonly AaplRow[]
