// Generated by scripts/sync-demo-data.mjs.
// Do not edit this file directly.
export interface AlphabetRow {
  readonly letter: string
  readonly frequency: number
}

export declare const alphabet: readonly AlphabetRow[]
