// Generated by scripts/sync-demo-data.mjs.
// Do not edit this file directly.
export interface AnscombeRow {
  readonly series: number
  readonly x: number
  readonly y: number
}

export declare const anscombe: readonly AnscombeRow[]
