// Generated by scripts/sync-demo-data.mjs.
// Do not edit this file directly.
export type BeagleRow = readonly [longitude: number, latitude: number]

export declare const beagle: readonly BeagleRow[]
