// Generated by scripts/sync-demo-data.mjs.
// Do not edit this file directly.
export interface CarsRow {
  readonly name: string
  readonly "economy (mpg)": number | null
  readonly cylinders: number
  readonly "displacement (cc)": number
  readonly "power (hp)": number | null
  readonly "weight (lb)": number
  readonly "0-60 mph (s)": number
  readonly year: number
}

export declare const cars: readonly CarsRow[]
