// Generated by scripts/sync-demo-data.mjs.
// Do not edit this file directly.
export interface CitywagesRow {
  readonly Metro: string
  readonly POP_1980: number
  readonly LPOP_1980: number
  readonly R90_10_1980: number
  readonly POP_2015: number
  readonly LPOP_2015: number
  readonly R90_10_2015: number
  readonly nyt_display: string
  readonly state_display: string | null
  readonly highlight: number | null
}

export declare const citywages: readonly CitywagesRow[]
