// Generated by scripts/sync-demo-data.mjs.
// Do not edit this file directly.
export interface CrimeanWarRow {
  readonly date: Date
  readonly army: number
  readonly disease: number
  readonly wounds: number
  readonly other: number
}

export declare const crimeanWar: readonly CrimeanWarRow[]
