// Generated by scripts/sync-demo-data.mjs.
// Do not edit this file directly.
export interface DecathlonRow {
  readonly Country: string
  readonly "100 Meters": number
  readonly "Long Jump": number
  readonly "High Jump": number
  readonly "100 Meter Hurdles": number
}

export declare const decathlon: readonly DecathlonRow[]
