// Generated by scripts/sync-demo-data.mjs.
// Do not edit this file directly.
export interface DiamondsRow {
  readonly carat: number
  readonly cut: string
  readonly color: string
  readonly clarity: string
  readonly depth: number
  readonly table: number
  readonly price: number
  readonly x: number
  readonly y: number
  readonly z: number
}

export declare const diamonds: readonly DiamondsRow[]
