// Generated by scripts/sync-demo-data.mjs.
// Do not edit this file directly.
export interface DownloadsRow {
  readonly date: Date
  readonly downloads: number
}

export declare const downloads: readonly DownloadsRow[]
