// Generated by scripts/sync-demo-data.mjs.
// Do not edit this file directly.
export interface DrivingRow {
  readonly side: string
  readonly year: number
  readonly miles: number
  readonly gas: number
}

export declare const driving: readonly DrivingRow[]
