// Generated by scripts/sync-demo-data.mjs.
// Do not edit this file directly.
export interface FlareRow {
  readonly name: string
  readonly size: number | null
}

export declare const flare: readonly FlareRow[]
