// Generated by scripts/sync-demo-data.mjs.
// Do not edit this file directly.
export interface IndustriesRow {
  readonly date: Date
  readonly industry: string
  readonly unemployed: number
}

export declare const industries: readonly IndustriesRow[]
