// Generated by scripts/sync-demo-data.mjs.
// Do not edit this file directly.
export interface LearningPovertyRow {
  readonly "Country Name": string
  readonly "Out-of-School (OoS)": number
  readonly "Below Minimum Proficiency (in School)": number
  readonly "Learning Poverty": number
  readonly "Assessment Year": number
  readonly Assessment: string
  readonly population: number
  readonly density: number
}

export declare const learningPoverty: readonly LearningPovertyRow[]
