// Generated by scripts/sync-demo-data.mjs.
// Do not edit this file directly.
export const demoDatasetMetadata = [
  {id: "aapl", title: "Apple daily stock prices", specifier: "@tanstack/charts-data/aapl", format: "CSV", records: 1260, fields: [
  "Date",
  "Open",
  "High",
  "Low",
  "Close",
  "Adj Close",
  "Volume",
], schema: [
  {name: "Date", types: [
  "Date",
]},
  {name: "Open", types: [
  "number",
]},
  {name: "High", types: [
  "number",
]},
  {name: "Low", types: [
  "number",
]},
  {name: "Close", types: [
  "number",
]},
  {name: "Adj Close", types: [
  "number",
]},
  {name: "Volume", types: [
  "number",
]},
], bytes: 92399, sha256: "18dc8bf6542da26625d992544a619a5fc210d6dfc799e81ab7fb7f9edbc21f9a", selection: "Complete published snapshot", source: "Yahoo! Finance", sourceUrl: "https://finance.yahoo.com/lookup", observablePackage: "@observablehq/sample-datasets@1.0.1", observableRevision: "732c0148de741469b2bcc03f53d93b0ad0b93f0a", observableFile: "aapl.csv", observableUrl: "https://github.com/observablehq/sample-datasets/blob/732c0148de741469b2bcc03f53d93b0ad0b93f0a/aapl.csv", license: "ISC distribution; upstream source credited"},
  {id: "alphabet", title: "English letter frequencies", specifier: "@tanstack/charts-data/alphabet", format: "CSV", records: 26, fields: [
  "letter",
  "frequency",
], schema: [
  {name: "letter", types: [
  "string",
]},
  {name: "frequency", types: [
  "number",
]},
], bytes: 275, sha256: "d62ce74dad83964bb0c463811933a29df888bff0624febbe7e63594931fa7e9e", selection: "Complete published snapshot", source: "Cryptographical Mathematics by Robert Edward Lewand", sourceUrl: "http://cs.wellesley.edu/~fturbak/codman/letterfreq.html", observablePackage: "@observablehq/sample-datasets@1.0.1", observableRevision: "732c0148de741469b2bcc03f53d93b0ad0b93f0a", observableFile: "alphabet.csv", observableUrl: "https://github.com/observablehq/sample-datasets/blob/732c0148de741469b2bcc03f53d93b0ad0b93f0a/alphabet.csv", license: "ISC distribution; upstream source credited"},
  {id: "cars", title: "1983 ASA automobile data", specifier: "@tanstack/charts-data/cars", format: "CSV", records: 406, fields: [
  "name",
  "economy (mpg)",
  "cylinders",
  "displacement (cc)",
  "power (hp)",
  "weight (lb)",
  "0-60 mph (s)",
  "year",
], schema: [
  {name: "name", types: [
  "string",
]},
  {name: "economy (mpg)", types: [
  "number",
  "null",
]},
  {name: "cylinders", types: [
  "number",
]},
  {name: "displacement (cc)", types: [
  "number",
]},
  {name: "power (hp)", types: [
  "number",
  "null",
]},
  {name: "weight (lb)", types: [
  "number",
]},
  {name: "0-60 mph (s)", types: [
  "number",
]},
  {name: "year", types: [
  "number",
]},
], bytes: 17438, sha256: "eaad8395d37ee0f591ea143e8ce4f87d0909fb1daba085834b27c1da841f56af", selection: "Complete published snapshot", source: "1983 ASA Data Exposition", sourceUrl: "http://lib.stat.cmu.edu/datasets/", observablePackage: "@observablehq/sample-datasets@1.0.1", observableRevision: "732c0148de741469b2bcc03f53d93b0ad0b93f0a", observableFile: "cars.csv", observableUrl: "https://github.com/observablehq/sample-datasets/blob/732c0148de741469b2bcc03f53d93b0ad0b93f0a/cars.csv", license: "ISC distribution; upstream source credited"},
  {id: "citywages", title: "U.S. metropolitan wage inequality", specifier: "@tanstack/charts-data/citywages", format: "CSV", records: 195, fields: [
  "Metro",
  "POP_1980",
  "LPOP_1980",
  "R90_10_1980",
  "POP_2015",
  "LPOP_2015",
  "R90_10_2015",
  "nyt_display",
  "state_display",
  "highlight",
], schema: [
  {name: "Metro", types: [
  "string",
]},
  {name: "POP_1980", types: [
  "number",
]},
  {name: "LPOP_1980", types: [
  "number",
]},
  {name: "R90_10_1980", types: [
  "number",
]},
  {name: "POP_2015", types: [
  "number",
]},
  {name: "LPOP_2015", types: [
  "number",
]},
  {name: "R90_10_2015", types: [
  "number",
]},
  {name: "nyt_display", types: [
  "string",
]},
  {name: "state_display", types: [
  "string",
  "null",
]},
  {name: "highlight", types: [
  "number",
  "null",
]},
], bytes: 15389, sha256: "9b50329064c16166026a8fee22c1f99f08c5de53697ab24271634b27d7b94a0b", selection: "Complete published snapshot", source: "The New York Times", sourceUrl: "https://www.nytimes.com/2019/12/02/upshot/wealth-poverty-divide-american-cities.html", observablePackage: "@observablehq/sample-datasets@1.0.1", observableRevision: "732c0148de741469b2bcc03f53d93b0ad0b93f0a", observableFile: "citywages.csv", observableUrl: "https://github.com/observablehq/sample-datasets/blob/732c0148de741469b2bcc03f53d93b0ad0b93f0a/citywages.csv", license: "ISC distribution; upstream source credited"},
  {id: "diamonds", title: "ggplot2 diamonds", specifier: "@tanstack/charts-data/diamonds", format: "CSV", records: 53940, fields: [
  "carat",
  "cut",
  "color",
  "clarity",
  "depth",
  "table",
  "price",
  "x",
  "y",
  "z",
], schema: [
  {name: "carat", types: [
  "number",
]},
  {name: "cut", types: [
  "string",
]},
  {name: "color", types: [
  "string",
]},
  {name: "clarity", types: [
  "string",
]},
  {name: "depth", types: [
  "number",
]},
  {name: "table", types: [
  "number",
]},
  {name: "price", types: [
  "number",
]},
  {name: "x", types: [
  "number",
]},
  {name: "y", types: [
  "number",
]},
  {name: "z", types: [
  "number",
]},
], bytes: 2448483, sha256: "243996d7650e84e190a88d505b44c3a0be1bcfc7b4f32606d60d103a51494b9e", selection: "Complete published snapshot", source: "ggplot2", sourceUrl: "https://github.com/tidyverse/ggplot2/blob/master/data-raw/diamonds.csv", observablePackage: "@observablehq/sample-datasets@1.0.1", observableRevision: "732c0148de741469b2bcc03f53d93b0ad0b93f0a", observableFile: "diamonds.csv", observableUrl: "https://github.com/observablehq/sample-datasets/blob/732c0148de741469b2bcc03f53d93b0ad0b93f0a/diamonds.csv", license: "ISC distribution; upstream source credited"},
  {id: "flare", title: "Flare package hierarchy", specifier: "@tanstack/charts-data/flare", format: "CSV", records: 252, fields: [
  "name",
  "size",
], schema: [
  {name: "name", types: [
  "string",
]},
  {name: "size", types: [
  "number",
  "null",
]},
], bytes: 7989, sha256: "704349b51b709f2357ea6a4ef01f46e0ccbe0917dc08e4a44c1cbe0b954b8c13", selection: "Complete published snapshot", source: "Flare visualization toolkit", sourceUrl: "https://observablehq.com/@d3/treemap", observablePackage: "@observablehq/sample-datasets@1.0.1", observableRevision: "732c0148de741469b2bcc03f53d93b0ad0b93f0a", observableFile: "flare.csv", observableUrl: "https://github.com/observablehq/sample-datasets/blob/732c0148de741469b2bcc03f53d93b0ad0b93f0a/flare.csv", license: "ISC distribution; upstream source credited"},
  {id: "industries", title: "U.S. industry unemployment", specifier: "@tanstack/charts-data/industries", format: "CSV", records: 1708, fields: [
  "date",
  "industry",
  "unemployed",
], schema: [
  {name: "date", types: [
  "Date",
]},
  {name: "industry", types: [
  "string",
]},
  {name: "unemployed", types: [
  "number",
]},
], bytes: 53919, sha256: "4cfc13b6ebe0f8c231b52895cee5f67670e5a1bad86460a8982716c3d86d835f", selection: "Complete published snapshot", source: "U.S. Bureau of Labor Statistics", sourceUrl: "https://www.bls.gov/", observablePackage: "@observablehq/sample-datasets@1.0.1", observableRevision: "732c0148de741469b2bcc03f53d93b0ad0b93f0a", observableFile: "industries.csv", observableUrl: "https://github.com/observablehq/sample-datasets/blob/732c0148de741469b2bcc03f53d93b0ad0b93f0a/industries.csv", license: "ISC distribution; upstream source credited"},
  {id: "miserables", title: "Les Misérables character network", specifier: "@tanstack/charts-data/miserables", format: "JSON", records: 331, fields: [
  "nodes",
  "links",
], schema: [
  {name: "nodes", types: [
  "array",
]},
  {name: "links", types: [
  "array",
]},
], bytes: 18844, sha256: "e84d8083667ccd496313307bd7e7a036da77689b8acf3464fa0211fb0b61a675", selection: "Complete published snapshot", source: "Donald Knuth, Stanford Graph Base", sourceUrl: "https://www-cs-faculty.stanford.edu/~knuth/sgb.html", observablePackage: "@observablehq/sample-datasets@1.0.1", observableRevision: "732c0148de741469b2bcc03f53d93b0ad0b93f0a", observableFile: "miserables.json", observableUrl: "https://github.com/observablehq/sample-datasets/blob/732c0148de741469b2bcc03f53d93b0ad0b93f0a/miserables.json", license: "ISC distribution; upstream source credited"},
  {id: "olympians", title: "2016 Summer Olympians", specifier: "@tanstack/charts-data/olympians", format: "CSV", records: 11538, fields: [
  "id",
  "name",
  "nationality",
  "sex",
  "date_of_birth",
  "height",
  "weight",
  "sport",
  "gold",
  "silver",
  "bronze",
  "info",
], schema: [
  {name: "id", types: [
  "number",
]},
  {name: "name", types: [
  "string",
]},
  {name: "nationality", types: [
  "string",
]},
  {name: "sex", types: [
  "string",
]},
  {name: "date_of_birth", types: [
  "Date",
]},
  {name: "height", types: [
  "number",
  "null",
]},
  {name: "weight", types: [
  "number",
  "null",
]},
  {name: "sport", types: [
  "string",
]},
  {name: "gold", types: [
  "number",
]},
  {name: "silver", types: [
  "number",
]},
  {name: "bronze", types: [
  "number",
]},
  {name: "info", types: [
  "string",
  "null",
]},
], bytes: 841836, sha256: "29ff8d6298da8961d264be2849701614cce6ef939d6e52fb413f2071ec30f7ec", selection: "Complete published snapshot", source: "Matt Riggott / IOC", sourceUrl: "https://www.flother.is/2017/olympic-games-data/", observablePackage: "@observablehq/sample-datasets@1.0.1", observableRevision: "732c0148de741469b2bcc03f53d93b0ad0b93f0a", observableFile: "olympians.csv", observableUrl: "https://github.com/observablehq/sample-datasets/blob/732c0148de741469b2bcc03f53d93b0ad0b93f0a/olympians.csv", license: "ISC distribution; upstream source credited"},
  {id: "penguins", title: "Palmer penguins", specifier: "@tanstack/charts-data/penguins", format: "CSV", records: 344, fields: [
  "species",
  "island",
  "culmen_length_mm",
  "culmen_depth_mm",
  "flipper_length_mm",
  "body_mass_g",
  "sex",
], schema: [
  {name: "species", types: [
  "string",
]},
  {name: "island", types: [
  "string",
]},
  {name: "culmen_length_mm", types: [
  "number",
  "null",
]},
  {name: "culmen_depth_mm", types: [
  "number",
  "null",
]},
  {name: "flipper_length_mm", types: [
  "number",
  "null",
]},
  {name: "body_mass_g", types: [
  "number",
  "null",
]},
  {name: "sex", types: [
  "string",
  "null",
]},
], bytes: 13506, sha256: "dfee817d1c1422363886dfd1897b3bed1a54ff9a3a6b223b5b7900a88e55a24d", selection: "Complete published snapshot", source: "Dr. Kristen Gorman / Palmer Station LTER", sourceUrl: "https://github.com/allisonhorst/palmerpenguins", observablePackage: "@observablehq/sample-datasets@1.0.1", observableRevision: "732c0148de741469b2bcc03f53d93b0ad0b93f0a", observableFile: "penguins.csv", observableUrl: "https://github.com/observablehq/sample-datasets/blob/732c0148de741469b2bcc03f53d93b0ad0b93f0a/penguins.csv", license: "ISC distribution; upstream source credited"},
  {id: "pizza", title: "Pizza Paradise orders", specifier: "@tanstack/charts-data/pizza", format: "CSV", records: 29853, fields: [
  "order_date",
  "day_of_week",
  "category",
  "name",
  "price",
  "orders",
  "revenue",
], schema: [
  {name: "order_date", types: [
  "Date",
]},
  {name: "day_of_week", types: [
  "string",
]},
  {name: "category", types: [
  "string",
]},
  {name: "name", types: [
  "string",
]},
  {name: "price", types: [
  "number",
]},
  {name: "orders", types: [
  "number",
]},
  {name: "revenue", types: [
  "number",
]},
], bytes: 2329284, sha256: "50b49e7118acd32960ab3a97784c9507fb1b040fddffaa35603097acf98405f6", selection: "Complete published snapshot", source: "Observable Pizza Paradise", sourceUrl: "https://observablehq.com/@observablehq/pizza-paradise-data", observablePackage: "@observablehq/sample-datasets@1.0.1", observableRevision: "732c0148de741469b2bcc03f53d93b0ad0b93f0a", observableFile: "pizza.csv", observableUrl: "https://github.com/observablehq/sample-datasets/blob/732c0148de741469b2bcc03f53d93b0ad0b93f0a/pizza.csv", license: "ISC distribution; upstream source credited"},
  {id: "weather", title: "Seattle weather observations", specifier: "@tanstack/charts-data/weather", format: "CSV", records: 2922, fields: [
  "location",
  "date",
  "precipitation",
  "temp_max",
  "temp_min",
  "wind",
  "weather",
], schema: [
  {name: "location", types: [
  "string",
]},
  {name: "date", types: [
  "Date",
]},
  {name: "precipitation", types: [
  "number",
]},
  {name: "temp_max", types: [
  "number",
]},
  {name: "temp_min", types: [
  "number",
]},
  {name: "wind", types: [
  "number",
]},
  {name: "weather", types: [
  "string",
]},
], bytes: 121417, sha256: "27219f1ca8dbd94c9b6f4b9f4f52ab2f1eb33dfdcf719cd9fc6481ed50b74549", selection: "Complete published snapshot", source: "NOAA / Vega", sourceUrl: "https://github.com/vega/vega-datasets/blob/master/scripts/weather.py", observablePackage: "@observablehq/sample-datasets@1.0.1", observableRevision: "732c0148de741469b2bcc03f53d93b0ad0b93f0a", observableFile: "weather.csv", observableUrl: "https://github.com/observablehq/sample-datasets/blob/732c0148de741469b2bcc03f53d93b0ad0b93f0a/weather.csv", license: "ISC distribution; upstream source credited"},
  {id: "westport-house", title: "Westport House second-floor plan", specifier: "@tanstack/charts-data/westport-house", format: "JSON", records: 121, fields: [
  "type",
  "features",
], schema: [
  {name: "type", types: [
  "string",
]},
  {name: "features", types: [
  "array",
]},
], bytes: 63146, sha256: "066ea951b4affba3ee7c2bf981b8333681ce24e55903ffcddcc39f0475fb39a3", selection: "Complete published snapshot", source: "WRLD indoor maps API", sourceUrl: "https://github.com/wrld3d/wrld-indoor-maps-api", observablePackage: "observablehq/plot@356f579b1d94", observableRevision: "356f579b1d947ee05a914420eddff0f29cee300a", observableFile: "test/data/westport-house.json", observableUrl: "https://github.com/observablehq/plot/blob/356f579b1d947ee05a914420eddff0f29cee300a/test/data/westport-house.json", license: "Observable Plot repository ISC; upstream source credited"},
  {id: "anscombe", title: "Anscombe's quartet", specifier: "@tanstack/charts-data/anscombe", format: "CSV", records: 44, fields: [
  "series",
  "x",
  "y",
], schema: [
  {name: "series", types: [
  "number",
]},
  {name: "x", types: [
  "number",
]},
  {name: "y", types: [
  "number",
]},
], bytes: 422, sha256: "136943112c4dbaebddb3f69f72612c0a4c9d4354b74ea54d98f6d16d01be9913", selection: "Complete published snapshot", source: "Anscombe's quartet", sourceUrl: "https://en.wikipedia.org/wiki/Anscombe%27s_quartet", observablePackage: "observablehq/plot@356f579b1d94", observableRevision: "356f579b1d947ee05a914420eddff0f29cee300a", observableFile: "test/data/anscombe.csv", observableUrl: "https://github.com/observablehq/plot/blob/356f579b1d947ee05a914420eddff0f29cee300a/test/data/anscombe.csv", license: "Observable Plot repository ISC; upstream source credited"},
  {id: "beagle", title: "HMS Beagle voyage", specifier: "@tanstack/charts-data/beagle", format: "CSV", records: 303, fields: [
  "0",
  "1",
], schema: [
  {name: "0", types: [
  "number",
]},
  {name: "1", types: [
  "number",
]},
], bytes: 4063, sha256: "338919940e130c887f186729eda26ad85b8b272ab83128d5facf40fbb3b309e9", selection: "Complete published snapshot", source: "Charles Darwin's voyage on the HMS Beagle", sourceUrl: "https://observablehq.com/@bmschmidt/data-driven-projections-darwins-world", observablePackage: "observablehq/plot@356f579b1d94", observableRevision: "356f579b1d947ee05a914420eddff0f29cee300a", observableFile: "test/data/beagle.csv", observableUrl: "https://github.com/observablehq/plot/blob/356f579b1d947ee05a914420eddff0f29cee300a/test/data/beagle.csv", license: "Observable Plot repository ISC; upstream source credited"},
  {id: "crimean-war", title: "Crimean War monthly mortality", specifier: "@tanstack/charts-data/crimean-war", format: "CSV", records: 24, fields: [
  "date",
  "army",
  "disease",
  "wounds",
  "other",
], schema: [
  {name: "date", types: [
  "Date",
]},
  {name: "army", types: [
  "number",
]},
  {name: "disease", types: [
  "number",
]},
  {name: "wounds", types: [
  "number",
]},
  {name: "other", types: [
  "number",
]},
], bytes: 676, sha256: "5747ee54b77a9b717dbc9d7f032581c4db67ea97de2f34df89cad093e632c368", selection: "Complete published snapshot", source: "Florence Nightingale", sourceUrl: "https://archive.org/details/b21304110/page/n11/mode/2up", observablePackage: "observablehq/plot@356f579b1d94", observableRevision: "356f579b1d947ee05a914420eddff0f29cee300a", observableFile: "test/data/crimean-war.csv", observableUrl: "https://github.com/observablehq/plot/blob/356f579b1d947ee05a914420eddff0f29cee300a/test/data/crimean-war.csv", license: "Observable Plot repository ISC; upstream source credited"},
  {id: "decathlon", title: "Decathlon results", specifier: "@tanstack/charts-data/decathlon", format: "CSV", records: 50, fields: [
  "Country",
  "100 Meters",
  "Long Jump",
  "High Jump",
  "100 Meter Hurdles",
], schema: [
  {name: "Country", types: [
  "string",
]},
  {name: "100 Meters", types: [
  "number",
]},
  {name: "Long Jump", types: [
  "number",
]},
  {name: "High Jump", types: [
  "number",
]},
  {name: "100 Meter Hurdles", types: [
  "number",
]},
], bytes: 1321, sha256: "8c016fb7adcc04f0a9a970cd50a7067b1faa019f7a1df924d4dafcfedfdde951", selection: "Complete published snapshot", source: "JMP Statistical Discovery sample", sourceUrl: "https://github.com/hemanrobinson/preattentive/blob/a58dd4795d0ee063a38a2d7bf33812d969ca6256/src/Data.js#L5598-L5650", observablePackage: "observablehq/plot@356f579b1d94", observableRevision: "356f579b1d947ee05a914420eddff0f29cee300a", observableFile: "test/data/decathlon.csv", observableUrl: "https://github.com/observablehq/plot/blob/356f579b1d947ee05a914420eddff0f29cee300a/test/data/decathlon.csv", license: "Observable Plot repository ISC; upstream source credited"},
  {id: "downloads", title: "Observable package downloads", specifier: "@tanstack/charts-data/downloads", format: "CSV", records: 1566, fields: [
  "date",
  "downloads",
], schema: [
  {name: "date", types: [
  "Date",
]},
  {name: "downloads", types: [
  "number",
]},
], bytes: 20457, sha256: "09953cc843f382738c48dcfeae633dea30579ada163e8fd53b9907fa5f11d6ca", selection: "Complete published snapshot", source: "npm downloads API", sourceUrl: "https://observablehq.com/@mbostock/npm-daily-downloads?name=@observablehq/cars", observablePackage: "observablehq/plot@356f579b1d94", observableRevision: "356f579b1d947ee05a914420eddff0f29cee300a", observableFile: "test/data/downloads.csv", observableUrl: "https://github.com/observablehq/plot/blob/356f579b1d947ee05a914420eddff0f29cee300a/test/data/downloads.csv", license: "Observable Plot repository ISC; upstream source credited"},
  {id: "learning-poverty", title: "Learning poverty by country", specifier: "@tanstack/charts-data/learning-poverty", format: "CSV", records: 100, fields: [
  "Country Name",
  "Out-of-School (OoS)",
  "Below Minimum Proficiency (in School)",
  "Learning Poverty",
  "Assessment Year",
  "Assessment",
  "population",
  "density",
], schema: [
  {name: "Country Name", types: [
  "string",
]},
  {name: "Out-of-School (OoS)", types: [
  "number",
]},
  {name: "Below Minimum Proficiency (in School)", types: [
  "number",
]},
  {name: "Learning Poverty", types: [
  "number",
]},
  {name: "Assessment Year", types: [
  "number",
]},
  {name: "Assessment", types: [
  "string",
]},
  {name: "population", types: [
  "number",
]},
  {name: "density", types: [
  "number",
]},
], bytes: 4675, sha256: "6c4d1c0aef44a435a3205f8af2a2321d56da01950fb60475bb5086b90ed07e50", selection: "Complete published snapshot", source: "World Bank / Our World in Data", sourceUrl: "https://ourworldindata.org/grapher/share-of-children-who-cannot-read-at-end-of-primary-age", observablePackage: "observablehq/plot@356f579b1d94", observableRevision: "356f579b1d947ee05a914420eddff0f29cee300a", observableFile: "test/data/learning-poverty.csv", observableUrl: "https://github.com/observablehq/plot/blob/356f579b1d947ee05a914420eddff0f29cee300a/test/data/learning-poverty.csv", license: "Observable Plot repository ISC; upstream source credited"},
  {id: "driving", title: "U.S. driving and gasoline prices", specifier: "@tanstack/charts-data/driving", format: "CSV", records: 55, fields: [
  "side",
  "year",
  "miles",
  "gas",
], schema: [
  {name: "side", types: [
  "string",
]},
  {name: "year", types: [
  "number",
]},
  {name: "miles", types: [
  "number",
]},
  {name: "gas", types: [
  "number",
]},
], bytes: 1546, sha256: "3aced2fa41f2be51ee43f9da66d964d7c647dac27bcc37158d09098efad4ba4e", selection: "Complete published snapshot", source: "The New York Times", sourceUrl: "https://archive.nytimes.com/www.nytimes.com/imagepages/2010/05/02/business/02metrics.html", observablePackage: "observablehq/plot@356f579b1d94", observableRevision: "356f579b1d947ee05a914420eddff0f29cee300a", observableFile: "test/data/driving.csv", observableUrl: "https://github.com/observablehq/plot/blob/356f579b1d947ee05a914420eddff0f29cee300a/test/data/driving.csv", license: "Observable Plot repository ISC; upstream source credited"},
  {id: "morley", title: "Michelson speed-of-light experiments", specifier: "@tanstack/charts-data/morley", format: "CSV", records: 100, fields: [
  "Expt",
  "Run",
  "Speed",
], schema: [
  {name: "Expt", types: [
  "number",
]},
  {name: "Run", types: [
  "number",
]},
  {name: "Speed", types: [
  "number",
]},
], bytes: 874, sha256: "a9c06023c0f277f09b6ad541e0f81acc4e21b09f3d5c35919547c3934dae5968", selection: "Complete published snapshot", source: "R datasets / Michelson–Morley experiment", sourceUrl: "https://github.com/vincentarelbundock/Rdatasets/blob/master/csv/datasets/morley.csv", observablePackage: "observablehq/plot@356f579b1d94", observableRevision: "356f579b1d947ee05a914420eddff0f29cee300a", observableFile: "test/data/morley.csv", observableUrl: "https://github.com/observablehq/plot/blob/356f579b1d947ee05a914420eddff0f29cee300a/test/data/morley.csv", license: "Observable Plot repository ISC; upstream source credited"},
  {id: "sf-temperatures", title: "San Francisco daily temperatures", specifier: "@tanstack/charts-data/sf-temperatures", format: "CSV", records: 732, fields: [
  "date",
  "high",
  "low",
], schema: [
  {name: "date", types: [
  "Date",
]},
  {name: "high", types: [
  "number",
]},
  {name: "low", types: [
  "number",
]},
], bytes: 15106, sha256: "1e90d4f9b2094bb32a4fd3f9d777478d0b5cb16f609c95e9be6eb2c245061cb4", selection: "Complete published snapshot", source: "National Climatic Data Center", sourceUrl: "https://www.ncdc.noaa.gov/", observablePackage: "observablehq/plot@356f579b1d94", observableRevision: "356f579b1d947ee05a914420eddff0f29cee300a", observableFile: "test/data/sf-temperatures.csv", observableUrl: "https://github.com/observablehq/plot/blob/356f579b1d947ee05a914420eddff0f29cee300a/test/data/sf-temperatures.csv", license: "Observable Plot repository ISC; upstream source credited"},
  {id: "simpsons", title: "The Simpsons episode ratings", specifier: "@tanstack/charts-data/simpsons", format: "CSV", records: 600, fields: [
  "id",
  "title",
  "original_air_date",
  "production_code",
  "season",
  "number_in_season",
  "number_in_series",
  "us_viewers_in_millions",
  "views",
  "imdb_rating",
  "imdb_votes",
  "image_url",
  "video_url",
], schema: [
  {name: "id", types: [
  "number",
]},
  {name: "title", types: [
  "string",
]},
  {name: "original_air_date", types: [
  "Date",
]},
  {name: "production_code", types: [
  "string",
]},
  {name: "season", types: [
  "number",
]},
  {name: "number_in_season", types: [
  "number",
]},
  {name: "number_in_series", types: [
  "number",
]},
  {name: "us_viewers_in_millions", types: [
  "number",
  "null",
]},
  {name: "views", types: [
  "number",
  "null",
]},
  {name: "imdb_rating", types: [
  "number",
  "null",
]},
  {name: "imdb_votes", types: [
  "number",
  "null",
]},
  {name: "image_url", types: [
  "string",
  "null",
]},
  {name: "video_url", types: [
  "string",
  "null",
]},
], bytes: 119729, sha256: "7cc6ecdcb70637a6d5e8df8933537f338178a96f61dd92e905f1b6b6044ebd31", selection: "Complete published snapshot", source: "IMDb / Todd W. Schneider", sourceUrl: "https://data.world/data-society/the-simpsons-by-the-data", observablePackage: "observablehq/plot@356f579b1d94", observableRevision: "356f579b1d947ee05a914420eddff0f29cee300a", observableFile: "test/data/simpsons.csv", observableUrl: "https://github.com/observablehq/plot/blob/356f579b1d947ee05a914420eddff0f29cee300a/test/data/simpsons.csv", license: "Observable Plot repository ISC; upstream source credited"},
  {id: "survey", title: "Likert survey responses", specifier: "@tanstack/charts-data/survey", format: "CSV", records: 500, fields: [
  "Question",
  "ID",
  "Response",
], schema: [
  {name: "Question", types: [
  "string",
]},
  {name: "ID", types: [
  "number",
]},
  {name: "Response", types: [
  "string",
]},
], bytes: 8217, sha256: "de6879d712488bf64cc7d215c12de59b5c9e08d574471493ae8d476510c2969c", selection: "Complete published snapshot", source: "Eitan Lees", sourceUrl: "https://talk.observablehq.com/t/diverging-stacked-bar-chart-in-plot/6028", observablePackage: "observablehq/plot@356f579b1d94", observableRevision: "356f579b1d947ee05a914420eddff0f29cee300a", observableFile: "test/data/survey.csv", observableUrl: "https://github.com/observablehq/plot/blob/356f579b1d947ee05a914420eddff0f29cee300a/test/data/survey.csv", license: "Observable Plot repository ISC; upstream source credited"},
  {id: "travelers", title: "U.S. airport traveler throughput", specifier: "@tanstack/charts-data/travelers", format: "CSV", records: 300, fields: [
  "date",
  "current",
  "previous",
], schema: [
  {name: "date", types: [
  "Date",
]},
  {name: "current", types: [
  "number",
]},
  {name: "previous", types: [
  "number",
]},
], bytes: 7836, sha256: "a5d9ba37fe6d67dc82195c571bc3f3a04ca07c83ddf57e127e1886f4d04d8ce8", selection: "Complete published snapshot", source: "U.S. Transportation Security Administration", sourceUrl: "https://www.tsa.gov/coronavirus/passenger-throughput", observablePackage: "observablehq/plot@356f579b1d94", observableRevision: "356f579b1d947ee05a914420eddff0f29cee300a", observableFile: "test/data/travelers.csv", observableUrl: "https://github.com/observablehq/plot/blob/356f579b1d947ee05a914420eddff0f29cee300a/test/data/travelers.csv", license: "Observable Plot repository ISC; upstream source credited"},
  {id: "us-county-unemployment", title: "U.S. county unemployment", specifier: "@tanstack/charts-data/us-county-unemployment", format: "CSV", records: 3219, fields: [
  "id",
  "state",
  "county",
  "rate",
], schema: [
  {name: "id", types: [
  "number",
]},
  {name: "state", types: [
  "string",
]},
  {name: "county", types: [
  "string",
]},
  {name: "rate", types: [
  "number",
]},
], bytes: 109819, sha256: "dd3cc76e5e21f8caceee84da7e36450d28a59a1535f928f93efbc9b752059452", selection: "Complete published snapshot", source: "U.S. Bureau of Labor Statistics", sourceUrl: "https://www.bls.gov/lau/tables.htm", observablePackage: "observablehq/plot@356f579b1d94", observableRevision: "356f579b1d947ee05a914420eddff0f29cee300a", observableFile: "test/data/us-county-unemployment.csv", observableUrl: "https://github.com/observablehq/plot/blob/356f579b1d947ee05a914420eddff0f29cee300a/test/data/us-county-unemployment.csv", license: "Observable Plot repository ISC; upstream source credited"},
  {id: "wind", title: "Gridded surface wind", specifier: "@tanstack/charts-data/wind", format: "CSV", records: 4800, fields: [
  "longitude",
  "latitude",
  "u",
  "v",
], schema: [
  {name: "longitude", types: [
  "number",
]},
  {name: "latitude", types: [
  "number",
]},
  {name: "u", types: [
  "number",
]},
  {name: "v", types: [
  "number",
]},
], bytes: 163963, sha256: "906a2dcf864ac82fd92b8863c30388665f004dbd85ac43ec43b87ce3aeea1a5a", selection: "Complete published snapshot", source: "Remote Sensing Systems / giCentre", sourceUrl: "https://github.com/gicentre/litvis/blob/main/examples/windVectors.md", observablePackage: "observablehq/plot@356f579b1d94", observableRevision: "356f579b1d947ee05a914420eddff0f29cee300a", observableFile: "test/data/wind.csv", observableUrl: "https://github.com/observablehq/plot/blob/356f579b1d947ee05a914420eddff0f29cee300a/test/data/wind.csv", license: "Observable Plot repository ISC; upstream source credited"},
]

const metadataBySpecifier = new Map(
  demoDatasetMetadata.map((dataset) => [dataset.specifier, dataset]),
)

export function demoDatasetForSpecifier(specifier) {
  return metadataBySpecifier.get(specifier) ?? null
}
