// Generated by scripts/sync-demo-data.mjs.
// Do not edit this file directly.
export interface DemoDatasetMetadata {
  readonly id: string
  readonly title: string
  readonly specifier: string
  readonly format: 'CSV' | 'JSON'
  readonly records: number
  readonly fields: readonly string[]
  readonly schema: readonly {
    readonly name: string
    readonly types: readonly string[]
  }[]
  readonly bytes: number
  readonly sha256: string
  readonly selection: string
  readonly source: string
  readonly sourceUrl: string
  readonly observablePackage: string
  readonly observableRevision: string
  readonly observableFile: string
  readonly observableUrl: string
  readonly license: string
}

export declare const demoDatasetMetadata: readonly DemoDatasetMetadata[]
export declare function demoDatasetForSpecifier(
  specifier: string,
): DemoDatasetMetadata | null
