// Generated by scripts/sync-demo-data.mjs.
// Do not edit this file directly.
export interface MiserablesNode {
  readonly id: string
  readonly group: number
}

export interface MiserablesLink {
  readonly source: string
  readonly target: string
  readonly value: number
}

export interface MiserablesGraph {
  readonly nodes: readonly MiserablesNode[]
  readonly links: readonly MiserablesLink[]
}

export declare const miserables: MiserablesGraph
