// Generated by scripts/sync-demo-data.mjs.
// Do not edit this file directly.
export interface MorleyRow {
  readonly Expt: number
  readonly Run: number
  readonly Speed: number
}

export declare const morley: readonly MorleyRow[]
