// Generated by scripts/sync-demo-data.mjs.
// Do not edit this file directly.
export interface OlympiansRow {
  readonly id: number
  readonly name: string
  readonly nationality: string
  readonly sex: string
  readonly date_of_birth: Date
  readonly height: number | null
  readonly weight: number | null
  readonly sport: string
  readonly gold: number
  readonly silver: number
  readonly bronze: number
  readonly info: string | null
}

export declare const olympians: readonly OlympiansRow[]
