// Generated by scripts/sync-demo-data.mjs.
// Do not edit this file directly.
export interface PenguinsRow {
  readonly species: string
  readonly island: string
  readonly culmen_length_mm: number | null
  readonly culmen_depth_mm: number | null
  readonly flipper_length_mm: number | null
  readonly body_mass_g: number | null
  readonly sex: string | null
}

export declare const penguins: readonly PenguinsRow[]
