// Generated by scripts/sync-demo-data.mjs.
// Do not edit this file directly.
export interface PizzaRow {
  readonly order_date: Date
  readonly day_of_week: string
  readonly category: string
  readonly name: string
  readonly price: number
  readonly orders: number
  readonly revenue: number
}

export declare const pizza: readonly PizzaRow[]
