// Generated by scripts/sync-demo-data.mjs.
// Do not edit this file directly.
export interface SfTemperaturesRow {
  readonly date: Date
  readonly high: number
  readonly low: number
}

export declare const sfTemperatures: readonly SfTemperaturesRow[]
