// Generated by scripts/sync-demo-data.mjs.
// Do not edit this file directly.
export interface SimpsonsRow {
  readonly id: number
  readonly title: string
  readonly original_air_date: Date
  readonly production_code: string
  readonly season: number
  readonly number_in_season: number
  readonly number_in_series: number
  readonly us_viewers_in_millions: number | null
  readonly views: number | null
  readonly imdb_rating: number | null
  readonly imdb_votes: number | null
  readonly image_url: string | null
  readonly video_url: string | null
}

export declare const simpsons: readonly SimpsonsRow[]
