// Generated by scripts/sync-demo-data.mjs.
// Do not edit this file directly.
export interface SurveyRow {
  readonly Question: string
  readonly ID: number
  readonly Response: string
}

export declare const survey: readonly SurveyRow[]
