// Generated by scripts/sync-demo-data.mjs.
// Do not edit this file directly.
export interface TravelersRow {
  readonly date: Date
  readonly current: number
  readonly previous: number
}

export declare const travelers: readonly TravelersRow[]
