// Generated by scripts/sync-demo-data.mjs.
// Do not edit this file directly.
export interface UsCountyUnemploymentRow {
  readonly id: number
  readonly state: string
  readonly county: string
  readonly rate: number
}

export declare const usCountyUnemployment: readonly UsCountyUnemploymentRow[]
