// Generated by scripts/sync-demo-data.mjs.
// Do not edit this file directly.
export interface WeatherRow {
  readonly location: string
  readonly date: Date
  readonly precipitation: number
  readonly temp_max: number
  readonly temp_min: number
  readonly wind: number
  readonly weather: string
}

export declare const weather: readonly WeatherRow[]
