// Generated by scripts/sync-demo-data.mjs.
// Do not edit this file directly.
export interface WestportHouseProperties {
  readonly id: number
  readonly type: string
  readonly name: string | null
  readonly roomnumber: string | null
}

export interface WestportHouseFeature {
  readonly type: 'Feature'
  readonly properties: WestportHouseProperties
  readonly geometry: {
    readonly type: 'Polygon'
    readonly coordinates: [number, number][][]
  }
}

export interface WestportHouseCollection {
  readonly type: 'FeatureCollection'
  readonly features: WestportHouseFeature[]
}

export declare const westportHouse: WestportHouseCollection
