// Generated by scripts/sync-demo-data.mjs.
// Do not edit this file directly.
export interface WindRow {
  readonly longitude: number
  readonly latitude: number
  readonly u: number
  readonly v: number
}

export declare const wind: readonly WindRow[]
